import { Store } from 'vuex'

const createStore = () => {
  return new Store({
    state: {
      fProducts: [
        {
          image: 'img/products/f1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
      ],
      nProducts: [
        {
          image: 'img/products/n1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
      ],
      allProducts: [
        {
          image: 'img/products/f1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/f8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/products/n8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t9.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t10.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t11.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t12.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t13.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t14.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t15.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t16.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t17.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t18.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t19.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t20.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t21.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t22.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t23.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t24.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t25.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t26.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t27.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t28.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t29.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t30.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t31.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t32.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t33.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t34.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t35.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t36.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t37.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t38.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t39.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t40.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t41.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t42.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t43.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t44.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t45.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t46.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t47.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t48.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t49.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/t50.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j9.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j10.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j11.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j12.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j13.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j14.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j15.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j16.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j17.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j18.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j19.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j20.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j21.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j22.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j23.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j24.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j25.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j26.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j27.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j28.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j29.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j30.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/j31.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p9.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p10.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p11.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/p12.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s1.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s2.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s3.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s4.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s5.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s6.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s7.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s8.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s9.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s10.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s11.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s12.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s13.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s14.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s15.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s16.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s17.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s18.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s19.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star4.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s20.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s21.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
        {
          image: 'img/product/s22.jpg',
          company: 'adidas',
          name: 'Cartoon Astronaut T-Shirt',
          icon: 'img/star/star5.png',
          price: '$100',
          cart: 'img/star/cart.png',
        },
      ],
      blogs: [
        {
          image: 'img/blog/b1.jpg',
          title: 'The Cotton-Jersey Zip-Up Hoodie',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
        },
        {
          image: 'img/blog/b2.jpg',
          title: 'The Cotton-Jersey Zip-Up Hoodie',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
        },
        {
          image: 'img/blog/b3.jpg',
          title: 'The Cotton-Jersey Zip-Up Hoodie',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
        },
        {
          image: 'img/blog/b4.jpg',
          title: 'The Cotton-Jersey Zip-Up Hoodie',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
        },
        {
          image: 'img/blog/b5.jpg',
          title: 'The Cotton-Jersey Zip-Up Hoodie',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
        },
        {
          image: 'img/blog/b6.jpg',
          title: 'The Cotton-Jersey Zip-Up Hoodie',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
        },
        {
          image: 'img/blog/b7.jpg',
          title: 'The Cotton-Jersey Zip-Up Hoodie',
          description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore.',
        },
      ],
    },
    mutations: {},
    getters: {},
    actions: {},
  })
}
export default createStore
